### ISSUE TITLE
MethodRules not supported

### ISSUE THREAD

**Issue by niom** [havarunner/havarunner#10]
When trying to use method rules with HavaRunner it fails due class cast exception.

java.lang.ClassCastException: fi.kesko.b2becom.ui.utils.ConditionalIgnoreRule cannot be cast to org.junit.rules.TestRule

	at com.github.havarunner.HavaRunner$.com$github$havarunner$HavaRunner$$applyRuleAndHandleException$1(HavaRunner.scala:144)
	at com.github.havarunner.HavaRunner$$anonfun$6.apply(HavaRunner.scala:152)
	at com.github.havarunner.HavaRunner$$anonfun$6.apply(HavaRunner.scala:151)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:110)
	at scala.collection.immutable.List.foldLeft(List.scala:83)
	at com.github.havarunner.HavaRunner$.runWithRules(HavaRunner.scala:150)
	at com.github.havarunner.HavaRunner$$anonfun$schedule$2$$anonfun$apply$3.apply(HavaRunner.scala:120)
	at com.github.havarunner.HavaRunner$$anonfun$schedule$2$$anonfun$apply$3.apply(HavaRunner.scala:116)
	at com.github.havarunner.ConcurrencyControl$.withThrottle(ConcurrencyControl.scala:21)
	at com.github.havarunner.HavaRunner$$anonfun$schedule$2.apply(HavaRunner.scala:116)
	at com.github.havarunner.HavaRunner$$anonfun$schedule$2.apply(HavaRunner.scala:116)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by laurilehmijoki** [comment]
Hello, why would you like to use `MethodRule` instead of `TestRule`? The [JUnit documentation](http://junit.org/junit4/javadoc/4.11/org/junit/rules/MethodRule.html) says: 

> Note that MethodRule has been replaced by TestRule, which has the added benefit of supporting class rules.

**Comment by niom** [comment]
Wanted to make custom annotations that would handle tests differently. Apparently the annotation is present in the TestRule Description. Noob fail. Sorry for bothering and thanks for pointing the obvious :)
